@startuml
start

:Acessar SIGO;
:Selecionar opção "Cadastrar";

:Escolher tipo de cadastro;
note right
Paciente ou Administrador
end note

if (Tipo é Paciente?) then (Sim)
        :Preencher dados do paciente;
    repeat
        :Validar informações;
        if (Dados válidos?) then (Sim)
            :Salvar cadastro do paciente;
            :Exibir mensagem de sucesso;
            break
        else (Não)
            :Exibir erros de validação;
        endif
    repeat while (Solicitar correção)

else (Tipo é Administrador)
    :Verificar permissões do usuário atual;
    if (Usuário tem permissão?) then (Sim)
            :Preencher dados do administrador;
        repeat
            :Validar informações;
            if (Dados válidos?) then (Sim)
                :Salvar cadastro do administrador;
                :Exibir mensagem de sucesso;
                break
            else (Não)
                :Exibir erros de validação;
            endif
        repeat while (Solicitar correção)

    else (Não)
        :Exibir mensagem "Permissão negada";
    endif
endif

stop
@enduml
